tables:

  silver_nyc_taxi:
    catalog: nyc_taxi
    schema: silver
    table: silver_nyc_taxi
    layer: silver
    partition_by:
      - periode

  gold_fact_trips:
    catalog: nyc_taxi
    schema: gold
    table: gold_fact_trips
    layer: gold
    partition_by:
      - periode

  gold_dim_date:
    catalog: nyc_taxi
    schema: gold
    table: gold_dim_date
    layer: gold

  gold_dim_location:
    catalog: nyc_taxi
    schema: gold
    table: gold_dim_location
    layer: gold

  gold_kpi_daily:
    catalog: nyc_taxi
    schema: gold
    table: gold_kpi_daily
    layer: gold
    partition_by:
      - periode

  audit_load:
    catalog: nyc_taxi
    schema: audit
    table: audit_load
    layer: audit

  audit_row_count:
    catalog: nyc_taxi
    schema: audit
    table: audit_row_count
    layer: audit