name: CI - NYC Taxi

on:
  push:
    branches:
      - dev
      - main

  pull_request:
    branches:
      - dev
      - main

jobs:
  python-checks:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: nyc_taxi/requirements.txt

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Install project dependencies
        run: |
          pip install -r nyc_taxi/requirements.txt


      - name: Install NYC Taxi package
        run: |
          pip install ./nyc_taxi

      - name: Run unit tests
        run: |
          python -m pytest -q nyc_taxi/tests

      - name: Compile Python files
        run: |
          python -m compileall -q nyc_taxi/src
          python -m compileall -q nyc_taxi/config

      - name: Test imports
        run: |
          python -c "import nyc_taxi; print('nyc_taxi import OK')"
          python -c "import nyc_taxi.src.common.spark_manager; print('SparkManager import OK')"
          python -c "import nyc_taxi.src.jobs.run_pipeline; print('Pipeline import OK')"
          python -c "import nyc_taxi.src.jobs.run_pipeline_airflow; print('Airflow runner import OK')"

  airflow-docker-checks:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: nyc_taxi/airflow

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate docker compose file
        run: |
          docker compose config

      - name: Build Airflow image
        run: |
          docker compose build

      - name: Test Airflow initialization
        run: |
          docker compose run --rm airflow-init