name: Run NYC Taxi Pipeline

on:
  workflow_dispatch:
    inputs:
      taxi_type:
        description: "Type de taxi"
        required: true
        default: "yellow"
        type: choice
        options:
          - yellow

      periode:
        description: "Période au format YYYYMM"
        required: true
        default: "202504"
        type: string

jobs:
  run-databricks-job:

    runs-on: ubuntu-latest

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
      DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}

    defaults:
      run:
        working-directory: nyc_taxi

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Databricks CLI
        uses: databricks/setup-cli@main

      - name: Run Databricks job
        run: |
          databricks bundle run nyc_taxi_job \
            --params taxi_type=${{ inputs.taxi_type }},periode=${{ inputs.periode }}


